name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout git repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pip install poetry==1.7.0

      - name: Prepare python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install project dependencies
        run: poetry install

      - name: Build and publish
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_API_TOKEN
          poetry publish --build
